import type { Config } from "tailwindcss"

const config: Config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "../../packages/ui/src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#f8f9ff",
        "surface-dim": "#ccdbf3",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d5e3fc",
        "on-surface": "#0d1c2e",
        "on-surface-variant": "#454651",
        "inverse-surface": "#233144",
        "inverse-on-surface": "#eaf1ff",
        outline: "#757682",
        "outline-variant": "#c5c5d3",
        "surface-tint": "#4459aa",
        primary: "#00134f",
        "on-primary": "#ffffff",
        "primary-container": "#0b2677",
        "on-primary-container": "#7d91e6",
        "inverse-primary": "#b7c4ff",
        secondary: "#0059bb",
        "on-secondary": "#ffffff",
        "secondary-container": "#0070ea",
        "on-secondary-container": "#fefcff",
        tertiary: "#2d1400",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#4b2500",
        "on-tertiary-container": "#e17d11",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "navy-deep": "#081B54",
        "navy-surface": "#0F3299",
        "blue-accent": "#007BFF",
        "blue-subtle": "#EBF4FF",
        "amber-primary": "#D97706",
        "amber-subtle": "#FEF3C7",
        "surface-canvas": "#F8FAFC",
        "surface-card": "#FFFFFF",
        "border-subtle": "#E2E8F0",
        "status-success": "#16A34A",
        "status-warning": "#EA580C",
        "status-danger": "#DC2626",
        "status-info": "#0284C7",
      },
      fontFamily: {
        "label-md": ["Plus Jakarta Sans", "Sarabun", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "Sarabun", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "Sarabun", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "Sarabun", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "Sarabun", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "Sarabun", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "Sarabun", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "Sarabun", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "Sarabun", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "Sarabun", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "Sarabun", "sans-serif"],
        sans: ["Plus Jakarta Sans", "Sarabun", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "30px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "display-lg-mobile": ["30px", { lineHeight: "38px", fontWeight: "700" }],
        "display-lg": ["40px", { lineHeight: "48px", fontWeight: "700" }],
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "gutter-desktop": "1.5rem",
        "gutter-mobile": "1rem",
        "container-max": "1440px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
    },
  },
  plugins: [],
}

export default config
